// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GxChatPresetEngineer(arg1, arg2, arg3) {
  return window['go']['main']['App']['GxChatPresetEngineer'](arg1, arg2, arg3);
}

export function GxChatSoundEngineer(arg1) {
  return window['go']['main']['App']['GxChatSoundEngineer'](arg1);
}

export function GxGetConfig() {
  return window['go']['main']['App']['GxGetConfig']();
}

export function GxGetDefaultOutputPath() {
  return window['go']['main']['App']['GxGetDefaultOutputPath']();
}

export function GxListModels(arg1, arg2) {
  return window['go']['main']['App']['GxListModels'](arg1, arg2);
}

export function GxOpenFolderOfFile(arg1) {
  return window['go']['main']['App']['GxOpenFolderOfFile'](arg1);
}

export function GxOpenPath(arg1) {
  return window['go']['main']['App']['GxOpenPath'](arg1);
}

export function GxSaveConfig(arg1) {
  return window['go']['main']['App']['GxSaveConfig'](arg1);
}

export function GxSaveFile(arg1, arg2) {
  return window['go']['main']['App']['GxSaveFile'](arg1, arg2);
}

export function GxSelectFolder(arg1) {
  return window['go']['main']['App']['GxSelectFolder'](arg1);
}

export function GxTestConnection(arg1, arg2) {
  return window['go']['main']['App']['GxTestConnection'](arg1, arg2);
}
