// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gemini} from '../models';
import {helix} from '../models';
import {config} from '../models';

export function GxChatPresetEngineer(arg1:gemini.RigDescription,arg2:string,arg3:Array<gemini.ChatMessage>):Promise<helix.Preset>;

export function GxChatSoundEngineer(arg1:Array<gemini.ChatMessage>):Promise<gemini.RigDescription>;

export function GxGetConfig():Promise<config.AppConfig>;

export function GxGetDefaultOutputPath():Promise<string>;

export function GxListModels():Promise<Array<string>>;

export function GxOpenFolderOfFile(arg1:string):Promise<void>;

export function GxOpenPath(arg1:string):Promise<void>;

export function GxSaveConfig(arg1:config.AppConfig):Promise<string>;

export function GxSaveFile(arg1:helix.Preset,arg2:string):Promise<string>;

export function GxSelectFolder(arg1:string):Promise<string>;

export function GxTestConnection():Promise<string>;
